apiVersion: v1
kind: Service
metadata:
  name: blue-vault-home
  namespace: blue-vault
spec:
  selector:
    app: blue-vault-home
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
